name: Update gh-pages with changes on master

on:
  push:
    branches: 
      - master

jobs:
  merge-changes-from-master:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Merge master
        env:
          GIT_AUTHOR_NAME: 'auto commit'
          GIT_COMMITTER_NAME: 'auto commit'
          EMAIL: 'noreply@localhost'
        run: >
          git fetch --depth=1 origin master:master

          git merge origin/master 
          --allow-unrelated-histories 
          --strategy-option=theirs
          --no-edit 

          git checkout -- tiles/ && git commit --amend --no-edit

          git push
